version: '3' 
services: 
  postgres: 
    image: postgres:15
    container_name: postgresdb
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - airflow-network
  
networks: 
  airflow-network: 
    external: false

volumes: 
  postgres_data: 